/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;


import Persistencia.Provincia;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author manuve
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
     public static void main(String[] args) 
   {
      EntityManagerFactory emfactory = Persistence.createEntityManagerFactory( "sistemataller1PU" );
      EntityManager entitymanager = emfactory.createEntityManager( );
      entitymanager.getTransaction( ).begin( );

      //Create Clas Entity
      Provincia clas1=new Provincia("misiones");
      Provincia clas2=new Provincia("catamarca");
      Provincia clas3=new Provincia("entre rios");

      //Store Clas
      entitymanager.persist(clas1);
      entitymanager.persist(clas2);
      entitymanager.persist(clas3);
      
   }
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuPrincipal = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jmenuCliente = new javax.swing.JMenu();
        jMenuINuevoCliente = new javax.swing.JMenuItem();
        jMenuIListaClientes = new javax.swing.JMenuItem();
        jMenuVehiculo = new javax.swing.JMenu();
        jMenuINuevoVehiculo = new javax.swing.JMenuItem();
        jMenuIListaVehiculos = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuVehiculoCaracteristicas = new javax.swing.JMenu();
        jMenuIABMMarca = new javax.swing.JMenuItem();
        jMenuIABMModelo = new javax.swing.JMenuItem();
        jMenuIABMSegmento = new javax.swing.JMenuItem();
        jMenuIABMEquipamiento = new javax.swing.JMenuItem();
        jMenuIABMAccesorios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuArchivo.setText("Archivo");

        jmenuCliente.setText("Cliente");

        jMenuINuevoCliente.setText("Nuevo");
        jMenuINuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuINuevoClienteActionPerformed(evt);
            }
        });
        jmenuCliente.add(jMenuINuevoCliente);

        jMenuIListaClientes.setText("Lista de clientes");
        jMenuIListaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIListaClientesActionPerformed(evt);
            }
        });
        jmenuCliente.add(jMenuIListaClientes);

        jMenuArchivo.add(jmenuCliente);

        jMenuVehiculo.setText("Vehiculo");

        jMenuINuevoVehiculo.setText("Nuevo");
        jMenuVehiculo.add(jMenuINuevoVehiculo);

        jMenuIListaVehiculos.setText("Lista de Vehiculos");
        jMenuIListaVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIListaVehiculosActionPerformed(evt);
            }
        });
        jMenuVehiculo.add(jMenuIListaVehiculos);
        jMenuVehiculo.add(jSeparator3);

        jMenuVehiculoCaracteristicas.setText("Caracteristicas");

        jMenuIABMMarca.setText("Marca");
        jMenuIABMMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIABMMarcaActionPerformed(evt);
            }
        });
        jMenuVehiculoCaracteristicas.add(jMenuIABMMarca);

        jMenuIABMModelo.setText("Modelo");
        jMenuVehiculoCaracteristicas.add(jMenuIABMModelo);

        jMenuIABMSegmento.setText("Segmento");
        jMenuIABMSegmento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIABMSegmentoActionPerformed(evt);
            }
        });
        jMenuVehiculoCaracteristicas.add(jMenuIABMSegmento);

        jMenuIABMEquipamiento.setText("Equipamiento");
        jMenuVehiculoCaracteristicas.add(jMenuIABMEquipamiento);

        jMenuIABMAccesorios.setText("Accesorios");
        jMenuVehiculoCaracteristicas.add(jMenuIABMAccesorios);

        jMenuVehiculo.add(jMenuVehiculoCaracteristicas);

        jMenuArchivo.add(jMenuVehiculo);

        jMenuPrincipal.add(jMenuArchivo);

        jMenu2.setText("Edit");
        jMenuPrincipal.add(jMenu2);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuIListaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIListaClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuIListaClientesActionPerformed

    private void jMenuINuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuINuevoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuINuevoClienteActionPerformed

    private void jMenuIListaVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIListaVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuIListaVehiculosActionPerformed

    private void jMenuIABMMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIABMMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuIABMMarcaActionPerformed

    private void jMenuIABMSegmentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIABMSegmentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuIABMSegmentoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new principal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuItem jMenuIABMAccesorios;
    private javax.swing.JMenuItem jMenuIABMEquipamiento;
    private javax.swing.JMenuItem jMenuIABMMarca;
    private javax.swing.JMenuItem jMenuIABMModelo;
    private javax.swing.JMenuItem jMenuIABMSegmento;
    private javax.swing.JMenuItem jMenuIListaClientes;
    private javax.swing.JMenuItem jMenuIListaVehiculos;
    private javax.swing.JMenuItem jMenuINuevoCliente;
    private javax.swing.JMenuItem jMenuINuevoVehiculo;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JMenu jMenuVehiculo;
    private javax.swing.JMenu jMenuVehiculoCaracteristicas;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu jmenuCliente;
    // End of variables declaration//GEN-END:variables
}
